### ISSUE TITLE
[Bug]: Closing the modal when configuring a custom modal leaves the overlay active

### ISSUE THREAD

**Issue by agentphoenix** [awcodes/scribble#20]
### What happened?

When closing the options modal for a custom block, the overlay remains active. This seems to happen either when inserting a block, updating an existing block, or closing the modal without changes.

### How to reproduce the bug

So far, I've been able to reproduce any time I close a modal. No customizations to modals with Scribble.

### Package Version

0.3.3-alpha

### PHP Version

8.3.3

### Laravel Version

10.48.2

### Which operating systems does with happen with?

macOS

**Comment by awcodes** [comment]
Hmm. I'm not seeing this issue.


https://github.com/awcodes/scribble/assets/3596800/3276098e-e186-4bec-9e85-ceed603cc1a9

**Comment by agentphoenix** [comment]
https://github.com/awcodes/scribble/assets/14422/97d13919-e5d6-4af9-a5ae-edad691b0b48

**Comment by awcodes** [comment]
Does it do it if it isn't a slideover?

**Comment by agentphoenix** [comment]
https://github.com/awcodes/scribble/assets/14422/c48eb45f-e56b-472d-bd41-5b1d058a65d3

Yep.

No console errors either.

**Comment by awcodes** [comment]
hmm. i can't replicate it. 

Will try to investigate further when i get some time.

**Comment by agentphoenix** [comment]
I'll do the same and see if I can identify any more details.

**Comment by agentphoenix** [comment]
Just a quick update... it looks like this is happening because I have both Scribble's modal on every page as well as the [Wire Elements modal](https://github.com/wire-elements/modal) on every page in my app.

**Comment by awcodes** [comment]
Interesting. The modals are based on wireuimodal but they have different views and ids. Not sure how they are tied together getting tied together.

**Comment by awcodes** [comment]
Worked on this today for Tiptap editor and mostly have models working with mounted form component actions. Once that is fully resolved should be easy enough to port over to scribble.
